name: Build Firmware

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - board: nice_nano_v2
            shield: corne_left
            
          - board: nice_nano_v2
            shield: corne_right
            
          - board: nrfmicro_13
            shield: sofle_left
            
          - board: nrfmicro_13
            shield: sofle_right

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Build
        uses: zmkfirmware/zmk/.github/actions/build-user-config@main
